feat: Enable Disk Caching for Multiple Sources (Supersedes PR#30)
paradedb/pg_analytics pull request #148
Opened 2024-10-08 07:44 UTC by shamb0

**This PR is part of a pair; please review, validate, and consider merging both.**

https://github.com/paradedb/paradedb/pull/1751

**Scope of this PR:**

This PR supersedes the following previous submissions:
- https://github.com/paradedb/paradedb/pull/1703
- https://github.com/paradedb/pg_analytics/pull/131

It is based on consolidated requirements and feedback from the review comments on the above closed PRs.

## What

- This PR separates the core implementation from [PR#30](https://github.com/paradedb/pg_analytics/pull/30), focusing on enabling disk caching for various sources supported by `pg_analytics`.
- The benchmarking, specifically for Hive-style partitioned Parquet sources, leverages this core disk cache functionality and is implemented in `paradedb/cargo-paradedb/src/pga_benches/pga_benchlogs_hsp_pq.rs`.

## Why

*To be filled out based on your rationale.*

## How

*To be filled out based on the technical approach.*

2024-10-09 21:09 UTC, philippemnoel commented on src/duckdb/json.rs
> +pub fn create_duckdb_relation(
Why are you renaming these functions? This again is making the diff much larger and harder to review. You're not even changing the code of the function, so why does it need a new name?

2024-10-09 21:10 UTC, philippemnoel commented on src/fdw/trigger.rs
> +}
If you think this is a better way to handle creating relations, could you please pull this out into a separate PR and submit it independently? This seems to me irrelevant to the feature at stakes here, which is making things harder to review

2024-10-09 21:11 UTC, philippemnoel commented on src/fdw/base.rs
> -
Why move this? It doesn't seem related to your new feature

2024-10-09 21:12 UTC, philippemnoel requested changes
Lots of code being moved around but seemingly not changed. Could you please share the rational why?

If you need to restructure things to enable your feature, which I can't quite tell at first glance, please submit a PR that this depends on. The diff on this PR is 800 lines yet I suspect you're only adding a much smaller fraction of new lines of code.

Please rescope this PR so it's reviewable.

2024-10-10 02:01 UTC, shamb0 commented
Hi @philippemnoel,

Thank you for the review comments, I really appreciate it. Moving forward, I'll aim for smaller PRs with minimal changes to make them easier to review.

2024-10-10 02:01 UTC, closed without merging